# Generated by Django 2.2.8 on 2020-04-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schronisko',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=15)),
                ('adres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('gatunek', models.CharField(max_length=30)),
                ('zdjecie', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=200)),
                ('czyDuzeMieszkanie', models.BooleanField()),
                ('czyDuzoCzasu', models.BooleanField()),
                ('czyDzieci', models.BooleanField()),
                ('schroniskoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamone.Schronisko')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('czyDuzeMieszkanie', models.BooleanField()),
                ('czyDuzoCzasu', models.BooleanField()),
                ('czyDzieci', models.BooleanField()),
                ('uzytkownikID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uzytkownikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zwierzeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamone.Zwierze')),
            ],
        ),
    ]
