# Generated by Django 2.2.7 on 2020-05-30 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencje',
            fields=[
                ('token_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('czyDuzeMieszkanie', models.BooleanField()),
                ('czyDuzoCzasu', models.BooleanField()),
                ('czyDzieci', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schronisko',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=15)),
                ('adres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('gatunek', models.CharField(max_length=30)),
                ('zdjecie', models.FileField(null=True, upload_to='')),
                ('opis', models.CharField(max_length=200)),
                ('czyDuzeMieszkanie', models.BooleanField()),
                ('czyDuzoCzasu', models.BooleanField()),
                ('czyDzieci', models.BooleanField()),
                ('schroniskoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamone.Schronisko')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzytkownikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zwierzeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamone.Zwierze')),
            ],
        ),
        migrations.CreateModel(
            name='BWLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czyLike', models.BooleanField()),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
                ('zwierzeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamone.Zwierze')),
            ],
        ),
    ]
