# Generated by Django 2.2.8 on 2020-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='zdjecie',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
