# Generated by Django 2.2.8 on 2020-05-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schronisko',
            old_name='login',
            new_name='nazwa',
        ),
    ]
